name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: GitGuardian Shield Action
      uses: GitGuardian/ggshield/actions/secret@main
      env:
        GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API }}

        
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.63.8
      with:
          base: ""
          head: ${{ github.ref_name }}

          
  SCA-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        runs-on: ubuntu-latest
        
    - name: Dependency analysis with npm audit
      run: npm audit

    - name: Dependency analysis with snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_API }}

  #sonacloud + codeql
  SAST-analysis:
      needs: [secret-scanning, SCA-analysis]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
        with:
           fetch-depth: 0

  build:
    needs: [SAST-analysis]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  test:
    needs: [build]
    runs-on: ubuntu-latest
    

#stack-hawk
  DAST-analysis:
      needs: [SAST-analysis]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
        with:
           fetch-depth: 0

  Azure-WebApp-Deployment:
    runs-on: ubuntu-latest
    needs: [test]
  

           
