name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Secret Scanning
    - name: GitGuardian Shield Action
      uses: GitGuardian/ggshield/actions/secret@main
      env:
        GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API }}

    - name: Get last 5 commits
      id: commit_ids
      run: |
        BASE_COMMIT=$(git rev-parse HEAD~5)
        echo "::set-output name=base_commit::$BASE_COMMIT"

        
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.63.8
      with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified
          
